# Generated by Django 3.1.7 on 2021-09-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgpages', '0002_orgpage_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgpage',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orgpage',
            name='alias',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
