# Generated by Django 3.1.7 on 2021-09-12 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgpages', '0003_auto_20210912_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgpage',
            name='alias',
        ),
    ]
